set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(RK3588_TOOLCHAIN_PREFIX "$ENV{RK3588_TOOLCHAIN_PREFIX}" CACHE STRING
    "AArch64 compiler prefix, for example /opt/toolchain/bin/aarch64-linux-gnu-")
set(RK3588_SYSROOT "$ENV{RK3588_SYSROOT}" CACHE PATH
    "RK3588 target sysroot")

if(RK3588_TOOLCHAIN_PREFIX STREQUAL "")
    set(RK3588_TOOLCHAIN_PREFIX "aarch64-linux-gnu-")
endif()

set(CMAKE_C_COMPILER "${RK3588_TOOLCHAIN_PREFIX}gcc")
set(CMAKE_CXX_COMPILER "${RK3588_TOOLCHAIN_PREFIX}g++")

if(NOT RK3588_SYSROOT STREQUAL "")
    set(CMAKE_SYSROOT "${RK3588_SYSROOT}")
    set(CMAKE_FIND_ROOT_PATH "${RK3588_SYSROOT}")
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
