set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(RV1126_TOOLCHAIN_PREFIX "$ENV{RV1126_TOOLCHAIN_PREFIX}" CACHE STRING "RV1126 cross compiler prefix")
set(RV1126_SYSROOT "$ENV{RV1126_SYSROOT}" CACHE PATH "RV1126 target sysroot")

if(NOT RV1126_TOOLCHAIN_PREFIX)
    message(FATAL_ERROR "Set RV1126_TOOLCHAIN_PREFIX, for example arm-linux-gnueabihf-")
endif()

set(CMAKE_C_COMPILER "${RV1126_TOOLCHAIN_PREFIX}gcc")
set(CMAKE_CXX_COMPILER "${RV1126_TOOLCHAIN_PREFIX}g++")

if(RV1126_SYSROOT)
    set(CMAKE_SYSROOT "${RV1126_SYSROOT}")
    set(CMAKE_FIND_ROOT_PATH "${RV1126_SYSROOT}")
    set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
    set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
    set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
    set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
endif()
